### ISSUE TITLE
No idea

### ISSUE THREAD

**Issue by kilbith** [Sokomine/mg_villages#1]
16:44:25: ACTION[ServerThread]: singleplayer joins game. List of players: singleplayer
TIME ELAPSED: 137 defines
TIME ELAPSED: 18016 generate_village
TIME ELAPSED: 20247 mark_buildings
TIME ELAPSED: 88 mark_dirt_roads
TIME ELAPSED: 84860 get_vmap_data
TIME ELAPSED: 97742 mark_inside_village_area
For village_nr 1, a height of 21 would be optimal. Sum: 2085 Count: 97. VS: 21
Majority vote for 1 is: 31 with 17 counts. Details: return { [6] = 1, [7] = 6, [8] = 3, [9] = 4, [10] = 1, [11] = 1, [12] = 1, [13] = 2, [14] = 2, [15] = 1, [16] = 3, [17] = 6, [18] = 4, [19] = 6, [20] = 5, [21] = 4, [22] = 3, [23] = 3, [24] = 3, [25] = 3, [26] = 1, [27] = 1, [28] = 2, [29] = 1, [30] = 4, [31] = 17, [32] = 9 } QMW: 23
TIME ELAPSED: 10756 get_height
CHANGING HEIGHT from 1 to 23
TIME ELAPSED: 49 change_height
16:44:26: ERROR[main]: ServerError: ...hare/minetest/games/minetest_game/mods/default/trees.lua:116: Deprecated use of default.grow_tree
16:44:26: ERROR[main]: stack traceback:
16:44:26: ERROR[main]:  [C]: in function 'error'
16:44:26: ERROR[main]:  ...hare/minetest/games/minetest_game/mods/default/trees.lua:116: in function 'grow_tree'
16:44:26: ERROR[main]:  /home/fabien/.minetest/mods/mg_villages/mapgen.lua:253: in function 'flatten_village_area'
16:44:26: ERROR[main]:  /home/fabien/.minetest/mods/mg_villages/mapgen.lua:744: in function 'place_villages_via_voxelmanip'
16:44:26: ERROR[main]:  /home/fabien/.minetest/mods/mg_villages/mapgen.lua:885: in function </home/fabien/.minetest/mods/mg_villages/mapgen.lua:878>
16:44:26: ERROR[main]:  /usr/share/minetest/builtin/game/register.lua:348: in function </usr/share/minetest/builtin/game/register.lua:336>
TIME ELAPSED: 129 defines
TIME ELAPSED: 14050 generate_village
TIME ELAPSED: 884 mark_buildings
TIME ELAPSED: 85 mark_dirt_roads
TIME ELAPSED: 87195 get_vmap_data
TIME ELAPSED: 77006 mark_inside_village_area
For village_nr 1, a height of 17 would be optimal. Sum: 2638 Count: 153. VS: 21
Majority vote for 1 is: 31 with 20 counts. Details: return { [6] = 4, [7] = 9, [8] = 8, [9] = 6, [10] = 15, [11] = 14, [12] = 3, [13] = 4, [14] = 4, [15] = 6, [16] = 12, [17] = 6, [18] = 10, [19] = 7, [20] = 1, [21] = 3, [22] = 3, [23] = 1, [24] = 2, [25] = 1, [26] = 1, [27] = 1, [29] = 2, [30] = 4, [31] = 20, [32] = 6 } QMW: 19
TIME ELAPSED: 11759 get_height
CHANGING HEIGHT from 1 to 19
TIME ELAPSED: 89 change_height
16:45:00: ERROR[main]: ServerMap::loadMapMeta(): could not open/home/fabien/.minetest/worlds/test/map_meta.txt

**Comment by HybridDog** [comment]
> 16:44:26: ERROR[main]: [C]: in function 'error'

When I edit mods, sometimes I get   error in error handling  , which is annoying and tells my an error at minetest.add_node every time instead of e.g. an mistake at a table index or a typo.
Maybe it depends on the modnames.

Edit: I noticed that an issue (fairly new) exists about that.
https://github.com/minetest/minetest/issues/1423
