### ISSUE TITLE
Requires grounds and deco (where?), ethereal, and forests

### ISSUE THREAD

**Issue by Poikilos** [Sokomine/mg_villages#17]
Hello, I am a little confused why this mod would still (optionally, as depends.txt has question marks for the mods/modpacks in question) use ethereal and forests, since moretrees does most of what both do and is lightweight. Also, I couldn't find grounds or deco on google along with the keyword minetest, even with quotes. I am not sure if homedecor will work in place of "deco" or not.

**Comment by Poikilos** [comment]
Also, snow is very old and snow by Splizard is very old, and there is now default:snow in minetest_game

**Comment by Sokomine** [comment]
Ethereal is foremost a mapgen. It creates an entirely diffrent world with diffrent biomes. The wood types in there provide nice material for villages. So do the wood types in the forest mod. Grounds and deco are part of Realtest - another nice mapgen/subgame that looks and works quite diffrent from the default game. If Realtest is used, diffrent materials need to be used for the houses and the mapgen as the default nodes are not available.

**Comment by Poikilos** [comment]
Thanks for the answer. Here's an outline of the answers, for visitors:
* The Realtest game for Minetest provides two dependencies:
  * **grounds**
  * **deco**
* mg_villages intentionally does not depend on minetest_game, so mg_villages:
  * has its own `snow`
  * uses **ethereal** (a mapgen) for some nice wood types
  * uses **forests** for some more nice wood types
