### ISSUE TITLE
mg_villages is in love with quartz:micro_pillars

### ISSUE THREAD

**Issue by verymilan** [Sokomine/mg_villages#18]
I think this design has room for improvements. ;)
![screenshot_20170403_203559](https://cloud.githubusercontent.com/assets/10698140/24625010/f7298230-18ad-11e7-9c06-de127ce867c4.png)

**Comment by Sokomine** [comment]
I'm sure those pillars could be a very nice addition and create worthy villages/cities. If you want them to be included, just build some suitable houses, save them with handle_schematics, put them in a folder, add a suitable init.lua file (see the other village_* mods for examples) - and there you go :-)

**Comment by Sokomine** [comment]
Ah. Now saw the screenshot. The villagers are definitely growing pillars as crops. Er. Why not :) Probably gives more money from passing players than just wheat? :)
Joke aside: This bug has been fixed in the meantime.
