### ISSUE TITLE
get_2d should be get2d in villages.lua and mapgen.lua

### ISSUE THREAD

**Issue by bokov-andrew** [Sokomine/mg_villages#25]
Was getting errors such as this one, even on a brand new flat world with only this and `handle_schematics` enabled:

    ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'mg_villages' in callback on_newplayer(): /home/a/.minetest/mods/mg_villages/villages.lua:27: attempt to call method 'get_2d' (a nil value)

After messing around with it a while, it's looking like the `get_2d` method doesn't actually exist (anymore?). Replacing it with `get2d` made the error go away and the villages start loading! Thought you'd like to know.  Using minetest v 0.4.16.

**Comment by Sokomine** [comment]
It's been a while since that. I checked, and get_2d still (or now?) exists. No deprecated warnings.
