### ISSUE TITLE
typo and support for fences mod

### ISSUE THREAD

**Issue by Danfun64** [Sokomine/mg_villages#4]
I recently ran mg_villages with blockman's 3d fences mod enabled, and the result was fences floating in the air.
http://i.imgur.com/1b2ePBU.png
Can you do something about it?
Also, do you want people to "abandom" plots?
http://i.imgur.com/FPbpHGR.png

**Comment by Sokomine** [comment]
The bug above doesn't have anything to do with the fences as such. It's a case of dirt missing below the fences and indeed a bug.
People ought to be able to abandom plots, but there needs to be a question added if they're really sure about it.

**Comment by Danfun64** [comment]
The reason I said "abandom" in quotation marks is because it's a typo. It's supposed to be abandon.

**Comment by Sokomine** [comment]
Thanks for telling! I'm not a native speaker, so please continue to have an eye on such errors.
The problem with the floating fences (which is more a case of "ground did not get placed properly" ought to be fixed with the most recent update as well.
