### ISSUE TITLE
traders

### ISSUE THREAD

**Issue by mahmutelmas06** [Sokomine/mg_villages#5]
Sometimes traders spawns on roofs

**Comment by Sokomine** [comment]
That happens whenever the random spot they choose to spawn on is inside a wall. Need to improve that and serach for an alternate place in such a case.

**Comment by Sokomine** [comment]
Please try the newest version. There will be less traders on roofs, although it can't yet be entirely avoided. In order to update, update mg_villages, handle_schematics and mobf_traders as those three interact in order to get the traders spawned.

**Comment by mahmutelmas06** [comment]
Ok. I will update it asap. Thank you for the fix.
