### ISSUE TITLE
Floating mountain parts

### ISSUE THREAD

**Issue by mahmutelmas06** [Sokomine/mg_villages#6]
I am using Valleys_mapgen which is compatible with this mod.
But as u see at the pictures mountain parts floats on sky. And again mountain parts becames huge stuns.

![screenshot_20150602_173445](https://cloud.githubusercontent.com/assets/11191763/7938395/f2ff1e52-094d-11e5-8174-d6b38a3dc203.png)
![screenshot_20150602_173535](https://cloud.githubusercontent.com/assets/11191763/7938448/2d49e77c-094e-11e5-8786-8fe5959b9c1d.png)

**Comment by Sokomine** [comment]
Those floating mountain tops are caused by the villages only acting on the mapchunk that contains the height level 0. That was fine with the "old" mapgen, but does look odd in newer mapgens. I might have to change this behaviour.

**Comment by Sokomine** [comment]
The newest version got extra handling for the mapchunks above the village. If you have extremly high mountains, you may have to set the variable
mg_villages.MAX_HEIGHT_TREATED = 200
in config.lua to a higher value. If you're using mapgen v6, a value of 64 might be sufficient.
