### ISSUE TITLE
Not an issue 

### ISSUE THREAD

**Issue by mahmutelmas06** [Sokomine/mg_villages#9]
Its not an issue but maybe you should know

18:45:04: WARNING: Assignment to undeclared global "trustedusers" inside a function at ...etest\bin..\mods\Map_Modpack\mg_villages/protection.lua:47.
18:45:04: WARNING: Assignment to undeclared global "trustedUser" inside a function at ...etest\bin..\mods\Map_Modpack\mg_villages/protection.lua:48.

And a question
Rivers covers villages while using valleys_mapgen. Maybe there is a way to avoid placing villages from water_source or flowing.

**Comment by HybridDog** [comment]
if you insert the mapgen function into that table instead of using minetest.register_on_generated, you can make the function become executed earlier
https://github.com/HybridDog/fractured/blob/wsmapgen/mods/eastside/init.lua#L98

**Comment by Sokomine** [comment]
Ought to have been fixed in the meantime. The variables are now local.

As for register on generated - there isn't much I can do. The mod is supposed to work with as many mapgens as possible. It wants to work *after* mapgen has done its work.
